### ISSUE TITLE
部署好了,但是界面始终出不来

### ISSUE THREAD

**Issue by alpha302** [CTF-MissFeng/report#2]
环境:mac 11.4 mysql 8
![image](https://user-images.githubusercontent.com/55012418/123821064-aaf6f880-d92d-11eb-9995-c7a21d23d453.png)
我部署好了,但是访问router.go中的路径却没反应.
![image](https://user-images.githubusercontent.com/55012418/123821293-dc6fc400-d92d-11eb-98b8-39d4818b0bb4.png)
![image](https://user-images.githubusercontent.com/55012418/123821475-00330a00-d92e-11eb-9627-209608ce3ee0.png)
debug是空的
![image](https://user-images.githubusercontent.com/55012418/123822254-b39bfe80-d92e-11eb-81a1-4f38bd77ccfd.png)

**Comment by CTF-MissFeng** [comment]
> 环境:mac 11.4 mysql 8
> ![image](https://user-images.githubusercontent.com/55012418/123821064-aaf6f880-d92d-11eb-9995-c7a21d23d453.png)
> 我部署好了,但是访问router.go中的路径却没反应.
> ![image](https://user-images.githubusercontent.com/55012418/123821293-dc6fc400-d92d-11eb-98b8-39d4818b0bb4.png)
> ![image](https://user-images.githubusercontent.com/55012418/123821475-00330a00-d92e-11eb-9627-209608ce3ee0.png)
> debug是空的
> ![image](https://user-images.githubusercontent.com/55012418/123822254-b39bfe80-d92e-11eb-81a1-4f38bd77ccfd.png)

请保证执行程序和目录在同一级别目录下，看你截图，应该是自己编译的吧，web静态目录改变了
<img width="636" alt="QQ20210629-233206@2x" src="https://user-images.githubusercontent.com/38177965/123826466-5f931900-d932-11eb-8155-415211795781.png">

**Comment by alpha302** [comment]
用的你的release部署的,还是不行...













在 2021-06-29 23:36:16，"cq-feng" ***@***.***> 写道：

目录结构如下：

**Comment by alpha302** [comment]
![image](https://user-images.githubusercontent.com/55012418/123828653-4d19df00-d934-11eb-8cbc-f964dd586845.png)

**Comment by CTF-MissFeng** [comment]
奇怪了，debug显示web静态目录public在用户根目录下，而不是在桌面/report目录下，尝试将public目录复制到对应目录下试试看呢，你是不是设置了什么环境变量，导致gf这个web框架将public目录设置为用户目录下了

<img width="805" alt="QQ20210630-000716@2x" src="https://user-images.githubusercontent.com/38177965/123831677-27420980-d937-11eb-9c52-3c788172fb0b.png">

**Comment by alpha302** [comment]
好了,应该是mac的问题,我用pd虚拟机去试成功了
![image](https://user-images.githubusercontent.com/55012418/123832679-2fe70f80-d938-11eb-8442-efab0532c999.png)
mac 11.4 10.15.7 都没成功.具体未知.

**Comment by alpha302** [comment]
应该是环境变量的问题,现在mac成功了! 表哥早点休息啊.
